apiVersion: config.liqo.io/v1alpha1
kind: ClusterConfig
metadata:
  name: configuration
  labels:
    app: liqo.io
spec:
  advertisementConfig:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20
  agentConfig:
    dashboardConfig:
      namespace: {{ .Release.Namespace }}
      service: {{ .Values.liqodash_chart.agentConfig.service }}
      serviceAccount: {{ .Values.liqodash_chart.agentConfig.serviceAccount }}
      ingress: {{ .Values.liqodash_chart.agentConfig.ingress }}
      appLabel: {{ .Values.liqodash_chart.agentConfig.appLabel }}
  discoveryConfig:
    clusterName: {{ .Values.clusterName}}
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    allowUntrustedCA: true
    service: _liqo._tcp
    updateTime: 3
    waitTime: 2
  liqonetConfig:
    podCIDR: {{ .Values.podCIDR }}
    serviceCIDR: {{ .Values.serviceCIDR }}
    reservedSubnets:
    - {{ .Values.podCIDR }}
    - {{ .Values.serviceCIDR }}
  dispatcherConfig:
    resourcesToReplicate:
    - group: net.liqo.io
      version: v1alpha1
      resource: networkconfigs
