package client

import (
	clusterConfig "github.com/liqoTech/liqo/api/config/v1alpha1"
)

//createClusterConfigController creates a new CRDController for the Liqo ClusterConfig CRD.
func createClusterConfigController(kubeconfig string) (*CRDController, error) {
	controller := &CRDController{}
	//init client
	newClient, err := clusterConfig.CreateClusterConfigClient(kubeconfig)
	if err != nil {
		return nil, err
	}
	/*The CRDClient generated by CreateClusterConfigClient contains a cache which is already running, but
	with no handler functions. In order to allow further uses of it and to create a consistent starting status
	for each client, this cache is immediately stopped.*/
	close(newClient.Stop)
	controller.CRDClient = newClient
	controller.resource = string(CRClusterConfig)
	return controller, nil
}
